-- create servicegroups table
CREATE TABLE service_groups (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    folder VARCHAR(255) NOT NULL,
    email VARCHAR(80) NOT NULL,
    color VARCHAR(7) NOT NULL,
    logo VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT
);

-- create products table
CREATE TABLE products (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    service_group_id INT(11) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    image VARCHAR(255) NOT NULL,
    description TEXT,
    FOREIGN KEY (service_group_id) REFERENCES service_groups(id) ON DELETE CASCADE
);

-- insert data into the service_groups table
INSERT INTO service_groups (name, folder, email, color, logo, url, description) VALUES
('Angel Wishes', 'anglewishes', 'angelwishes@nist.ac.th', '#c2593a', './logo.png', './index.php', 'To raise awareness and promote learning on the realities of cancer and cancer treatment in the NIST community, in addition to providing social, emotional, and financial support to patients diagnosed with cancer and their loved ones, in partnership with Angel Foundation.'),
('Art Relief Crew (ARC)', 'arc', 'arc@nist.ac.th', '#435ba6', './logo.png', './index.php', 'Partnering with Steps, we aim to build an inclusive space embodying equality for the neurodiverse community.'),
('Baan SaiJai', 'baansaijai', 'baansaijai@nist.ac.th', '#bf8d42', './logo.png', './index.php', 'We aim to learn, collaborate and partner with many organisations in advocating and taking direct action for the issue of migrant workers, which can be sometimes overlooked, and supporting migrant communities financially and socially. '),
('Beat As One', 'beatasone', 'beatasone@nist.ac.th', '#435ba6', './logo.png', './index.php', 'We aim to provide basic medical supplies to those in need, making sure they know how to use it and the importance of it towards a better lifestyle. We hope to spread awareness and empower community members on the importance of wellness, our local medical heroes, and projects we could work on together towards SDG #3.'),
('c@tNIST', 'catnist', 'cat@nist.ac.th', '#769f57', './logo.png', './index.php', 'To create a safe and healthy environment for cats on NIST campus, and collaborating closely with PAWS Bangkok to provide direct and indirect assistance to cats in need. Through our efforts, we strive to share with the community the challenges surrounding soi cats, the importance of Adopt-Don’t-Shop, neuter/spay, and vaccination.'),
('Children of the Forest', 'cof', 'cof@nist.ac.th', '#c2593a', './logo.png', './index.php', 'Our aim is to raise awareness about the problems that the group of stateless individuals in the COF organisation face, as well as raise funds in order to support the organisation. We will make sure to be a key contributor to the projects on the ground and maintain a sustained effort in supporting the needs of COF.'),
('Connecting Communities', 'connectingcommunities', 'connectingcommunities@nist.ac.th', '#c2593a', './logo.png', './index.php', 'Our Vision is to help meet some of the needs of people living within the Khlong Toei Community. We would like to get to know the community better and establish strong links with them in order to  create a sustainable community giving the people more opportunities to become something more. "Empowering members of the Khlong Toey Community through  Communication, Collaborative Efforts, Co-Creation of Opportunities, Celebrating Achievements, and Embracing Positive Change to Build a Thriving Future Together." '),
('CURED', 'cured', 'cured@nist.ac.th', '#bf8d42', './logo.png', './index.php', 'We strive to reduce e-waste from entering landfills by reusing and recycling digital debris. To do this, we collect used devices from our community and test them to see if they are working. If they do not work, we ethically recycle them with an external vendor, saving them from landfills. If they do work, we sell them at a heavily discounted price, giving them a second life with a new user.'),
('E Co.', 'eco', 'eco@nist.ac.th', '#769f57', './logo.png', './index.php', 'To raise awareness on the importance of upcycling - transforming waste into reusable products in our school community, specifically paper.'),
('Edibubble', 'edibubble', 'edibubble@nist.ac.th', '#769f57', './logo.png', './index.php', 'To research, create and advocate for bio-friendly alternatives working towards rejuvenating the state of our planet and ecosystem.'),
('FairNIST', 'fairnist', 'fairnist@nist.ac.th', '#bf8d42', './logo.png', './index.php', 'FairNIST is a non-profit social enterprise that works in the spirit of fair trade to support local communities and farmers in Chiang Mai. We aim to learn together with coffee farmers through training, research, and development.'),
('FashioNIST', 'fashionist', 'fashion@nist.ac.th', '#bf8d42', './logo.png', './index.php', 'Raise awareness about the harms of fast fashion, support and celebrate local artisans who create slow fashion. Through education, learn together on skills needed for slow fashion such as weaving and dyeing, which are encouraged to diminish the amount of fabric waste.'),
('FemiNIST', 'feminist', 'feminist@nist.ac.th', '#c2593a', './logo.png', './index.php', 'To encourage gender equity amongst the NIST Community, while combating negative connotations in regards to feminism, gender roles and stereotypes. '),
('Forest Rangers', 'forestrangers', 'forestrangers@nist.ac.th', '#769f57', './logo.png', './index.php', 'We aim to support forest rangers in Thailand who live below the poverty line. Our key pursuit is to actively promote awareness of forest rangers and their vital contributions through advocacy efforts.'),
('Free To Be', 'freetobe', 'freetobe@nist.ac.th', '#c2593a', './logo.png', './index.php', 'To raise awareness about the LGBTQ+ community, especially within NIST, as well as to create a safe space for those who identify as part of the LGBTQ+ community. We aim to have a digital and social presence to keep the NIST community informed of world movements and news but also involve our community to ensure there is a constant understanding and alliance between us all. Our key target is to educate the members of our NIST community, but also the regional community by integrating a higher degree of LGBTQ+ information into the curriculum and collaborating with other service groups and schools to hold various events and awareness-raising campaigns. We collaborate with the GSA (MS) and the elementary service project, Rainbow Club.'),
('Friends of the Immanuel Orchestra', 'friendsoftheimmanuleorchestra', 'fio@nist.ac.th', '#435ba6', './logo.png', './index.php', 'Friends of the Immanuel Orchestra will aim to work with the Immanuel Orchestra financially and facilitate a bond with the NIST community while promoting musical development. Our values are involvement, personal improvement, and fundraising.'),
('Green Light', 'greenlight', 'greenlight@nist.ac.th', '#435ba6', './logo.png', './index.php', 'Mission Statement: "To empower survivors of human trafficking and sexual exploitation in Thailand to secure their fundamental human rights and advance the eradication of modern-day slavery. "Vision Statement: “To advocate for the eradication of human trafficking and sexual exploitation in Thailand, leveraging a combination of targeted advocacy, strategic fundraising, and comprehensive support services to raise widespread awareness within the NIST community. "This mission and vision are achieved through partnering with The New Life Center Foundation based in Chiang Mai, where we fundraise by selling handmade jewellery.'),
('Helping Hearts', 'helpinghearts', 'helpinghearts@nist.ac.th', '#c2593a', './logo.png', './index.php', 'Helping Hearts partners with Concordia Welfare Education Foundation of Thailand (CWEFT) towards learning and building relationships with children in the urban slum area and exploring opportunities to support in projects such as Xmas presents, hygiene packs, books and items that are in need.'),
('MushieMushie', 'mushiemushie', 'mushiemushie@nist.ac.th', '#769f57', './logo.png', './index.php', 'MushieMushie partners with FREELAND in learning and advocating for wildlife conservation in Khao Yai and the work together with indigenous community members in the region towards anti-poaching. We empower students with the awareness, knowledge, and opportunities to make meaningful difference.'),
('NEST', 'nest', 'nestservicegroup@nist.ac.th', '#769f57', './logo.png', './index.php', 'Mission: To advocate for endangered species in Thailand by selling animal themed products to the NIST community through our partnerships with Wildlife Friends Foundation Thailand (WFFT) and the Gibbon Rehabilitation Project (GRP) Phuket. Vision: To inform the NIST community on the illegal wildlife trade and promote responsible tourism by selling animal-themed products while partnering with WFFT and GRP Phuket to support the rescue and rehabilitation of Thailand’s endangered species.'),
('NISTCha', 'nistcha', 'cha@nist.ac.th','#bf8d42', './logo.png', './index.php', 'NISTCha strives to promote the sale of Fair Trade Tea in an effort to support tea farmers in Northern Thailand towards sustainable partnership and community wellbeing. Our goals include introducing high-quality tea, sharing brewing techniques, and contributing to the well-being of our communities. This helps create a positive and long-lasting impact on tea-drinking cultures.'),
('NIST Community Market', 'nistcomunitymarket', 'communitymarket@nist.ac.th', '#435ba6', './logo.png', './index.php', 'Our aim is to bring the community together and actively promote a sustainable community through the consumption of eco-friendly and organic goods. We do this by hosting community events that support local vendors, social enterprises, and other service groups. We believe that by supporting communities, there will be learning and sustainability for everyone.'),
('NIST Tech', 'nisttech', 'nisttech@nist.ac.th','#bf8d42', './logo.png', './index.php', 'Foster a passion for technology and computer engineering, increase technical know-how, and use technological knowledge to support the local community.'),
('Operation Smile', 'operationsmile', 'operationsmile@nist.ac.th', '#c2593a', './logo.png', './index.php', 'Operation Smile NIST works alongside Operation Smile Thailand, sharing the aim of working towards a world where no child suffers from lack of access to safe surgery. At Operation Smile NIST we support the greater organization of Operation Smile Thailand by raising money and awareness to support those with oral and facial malformations, mainly cleft lips and palates.'),
('PhuLiPhay', 'phuliphay', 'phuliphay@nist.ac.th','#c2593a', './logo.png', './index.php', 'PhuLiPhay’s aim is to advocate and raise awareness for urban and rural refugees and provide support through fundraising and interactions. This allows for a reciprocal partnership encouraging empowerment and fostering a motivation for driving social change.'),
('Plastic Free NIST', 'plasticfreenist', 'plasticfree@nist.ac.th','#769f57', './logo.png', './index.php', 'Plastic Free NIST works to eradicate the use of plastic at NIST and in the wider Bangkok community through providing sustainable alternatives while through education, continue to learn of the plastic problem as a school community.'),
('PRICEless','priceless', 'priceless@nist.ac.th', '#bf8d42', './logo.png', './index.php', 'To increase the quality of education at the Nongphainongwa Elementary School in the Roi Et province of Thailand by creating a sustainable organic rice partnership with the parent farmers of the school community. This small business will empower farmers and allow them to reinvest their profits into improving their agricultural practices and we use the profits to improve their school. By doing so, we also want to endorse the production and consumption of organic rice. We also want to help change their practices to benefit their environment, health and incomes.'),
('Rescued Glass', 'rescuedglass', 'rescuedglass@nist.ac.th','#435ba6', './logo.png', './index.php', 'To raise awareness of the importance of recycling by transforming them into usable and decorative household items.'),
('Revive', 'revive', 'revive@nist.ac.th','#769f57', './logo.png', './index.php', 'Mission: Our mission is to raise awareness of the importance of coral reef ecosystems and the threats they face. Vision: Our vision is to maintain the beauty and importance of coral reefs so that they can be enjoyed by future generations.'),
('Rooftop Garden', 'rooftopgarden', 'rooftopgarden@nist.ac.th', '#bf8d42', './logo.png', './index.php', 'We promote a sustainable farm-garden on the rooftop where organic and farm-to-table products can be accessible for the NIST community.'),
('S.O.A.P', 'soap', 'soap@nist.ac.th','#435ba6', './logo.png', './index.php', 'We aim to prevent trafficking of young girls in Northern Thailand by supporting and empowering those who have been victims or are at risk. This is achieved through partnering with Friends Of Thai Daughters and crafting eco-conscious soap products.'),
('Tusk', 'tusk', 'tusk@nist.ac.th', '#769f57', './logo.png', './index.php', 'Tusk strives to create a world in which people and elephants can live in harmony. We work with the organisation, Bring The Elephants Home, to come up with creative and peaceful solutions to mediate human-elephant conflict. We encourage the community to come up with their own creative solutions and work together in making it possible. We also aim to rebuild elephant habitat as a part of the proceeds go towards forest rehabilitation. '),
('WellNIST', 'wellnist', 'wellnist@nist.ac.th','#c2593a', './logo.png', './index.php', 'We strive to foster mental health literacy and enhance well-being by empowering individuals to identify challenges, understand the factors causing them, and provide resources that empower our community to address their challenges in a safe and supportive environment increasing mental wellbeing. We work with YouDee, a startup under the Thai Red Cross in understanding and expanding our outreach within the community.'),
('WISH Together', 'wishtogether', 'wishtogetherdwbi@nist.ac.th','#c2593a', './logo.png', './index.php', 'We aim to partner with schools in rural regions of Thailand and support them with materials that contribute to renovating/improving the learning environment. This will create a comfortable learning environment for all students to flourish. One school at a time.'),
('WOOF', 'woof', 'woof@nist.ac.th','#769f57', './logo.png', './index.php', 'Welfare Of Our Friends (WOOF) is a service initiative that aims to raise awareness about issues regarding Soi Dogs in Thailand. We work alongside Soi Dog shelters and foundations to improve the livelihood of homeless, neglected and abused dogs in Thailand.');

-- insert data into the products table
INSERT INTO products (service_group_id, name, price, image, description) VALUES
(6, 'Card Holder', 140, './images/product1.png', 'Children of the forest card holder.'),
(6, 'Tote Bag', 100, './images/product2.png', 'Children of the forest tote bag.'),
(16, 'FIO Stickers', 20, './images/product1.png', 'Cute stickers that are festive, musical and adorable!'),
(16, 'Custom Spotify Keychain', 120, './images/product2.png', 'Choose your own song/playlist and have on a keychain! You can scan on spotify to listen to your favourite songs!'),
(16, 'Spotify Keychain', 100, './images/product3.png', 'Scan on spotify to listen to songs! (Not Customizable)'),
(17, 'Hand-Stitched Heart Keychains', 80, './images/product1.png', 'Cross-stitched heart keychains made by the girls at the New Life Center for victims of human trafficking.'),
(17, 'Round Felt Ornaments', 160, './images/product2.png', 'Handsewn red felt ornaments, perfect for a Christmas tree or other decorative function, handmade by the girls at the New Life Center for victims of human trafficking.'),
(17, 'Paisley Pouches', 100, './images/product3.png', 'Handmade black paisley pouches that can be used to hold coins, and other small items.'),
(21, 'Jasmine Tea', 120, './images/product1.png', '10 reusable bags of Jasmine tea, a fragrant tea with a sweet, floral jasmine aroma.'),
(21, 'Tung Ting Oolong Tea', 150, './images/product2.png', '10 reusable bags of Oolong tea a creamy tea with subtle floral and fruity notes.'),
(21, 'Osmanthus Oolong Tea', 150, './images/product3.png', '10 reusable bags of Osmanthus Oolong tea is a beautifully fragrant blend that combines the floral sweetness of osmanthus blossoms with the complex depth of oolong tea.'),
(32, 'Coexistence Candle / Kui Buri Candle', 400, './images/product1.png', 'Coconut candles made with herbs from Thai farmers as part of the Tom Yum project. Kui Buri candle scented like citrus. Coexistence candle scented sharply like lemongrass and citronella.'),
(32, 'Kui Buri Soap / Holistic Honey Soap', 200, './images/product2.png', 'Soaps made with herbs from Thai farmers as part of the Tom Yum project. Kui Buri soap scented like citrus. Holistic Honey soap scented like honey and gentle herbs.'),
(32, 'Bring the Elephant Home T-shirt', 400, './images/product3.png', 'T-shirt supporting Bring The Elephants Home’s work with elephants in Thailand.'),
(33, 'Coffee Lover Soap', 120, './images/product1.png', 'Coffee Lover soap spa exfoliates dead skin cells, and antioxidants stimulate the activity of inner skin cells. The soap stimulates fat burning under the skin layer, making the skin look radiant.'),
(33, 'Ocean Blue Soap', 220, './images/product2.png', 'By rejuvenating the skin through exfoliation and having antioxidants stimulate the activity of inner skin cells, Ocean Blue soap increases collagen resulting in radiant, soft, and smooth skin.');